import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Usando a variável da fonte Inter e a classe font-sans
    <html lang="en" className={`${inter.variable} font-sans`}>
      <body className="  antialiased">{children}</body>
    </html>
  );
}
